- hosts: all
  become: yes
  tasks:
    - name: SSH KeyGen command
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
    - name: Fetch the keyfile from one server to another
      fetch: 
        src: "{{ ~/.ssh/id_rsa.pub }}"
        dest: "{{ buffer/{{ansible_hostname}}-id_rsa.pub }}"
        flat: yes
    - name: Disable Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup : yes
    - restart ssh
      handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
